USE ROLE TRAINING_ROLE;
USE WAREHOUSE ROOSTER_WH;

CREATE OR REPLACE DATABASE ROOSTER_PROJECT_DB;
CREATE OR REPLACE SCHEMA ROOSTER_PROJECT_DB.STAGING;
CREATE OR REPLACE SCHEMA ROOSTER_PROJECT_DB.DW;

USE DATABASE ROOSTER_PROJECT_DB;
USE SCHEMA STAGING;

-- Extract: staging tabuľka z Marketplace
CREATE OR REPLACE TABLE ZIP_CODE_METADATA_STAGING AS
SELECT * FROM U_S__ZIP_CODE_METADATA.ZIP_DEMOGRAPHICS.ZIP_CODE_METADATA;

CREATE OR REPLACE TABLE ZIP_CODE_METADATA_CLEAN AS
WITH src AS (
  SELECT
    TRIM(ZIP) AS ZIP,
    TRY_TO_DOUBLE(TRIM(LATITUDE))  AS LATITUDE,
    TRY_TO_DOUBLE(TRIM(LONGITUDE)) AS LONGITUDE,
    INITCAP(TRIM(CITY)) AS CITY,
    UPPER(TRIM(STATE)) AS STATE,
    TRIM(TIMEZONE) AS TIMEZONE,
    TRIM(DAYLIGHT_SAVINGS) AS DAYLIGHT_SAVINGS_RAW,
    TRIM(GEOPOINT) AS GEOPOINT,
    TRY_TO_NUMBER(TRIM(DMA_ID)) AS DMA_ID,
    TRIM(DMA_NAME) AS DMA_NAME,
    TOTAL_POPULATION,
    MEDIAN_AGE,
    TOTAL_MALE_POPULATION,
    TOTAL_FEMALE_POPULATION,
    -- pomocné flagy
    IFF(UPPER(TRIM(DAYLIGHT_SAVINGS)) IN ('Y','YES','TRUE','T','1'), 1, 0) AS IS_DAYLIGHT_SAVINGS
  FROM ZIP_CODE_METADATA_STAGING
),
dedup AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY ZIP
      ORDER BY
        IFF(TOTAL_POPULATION IS NOT NULL, 1, 0) DESC,
        IFF(LATITUDE IS NOT NULL AND LONGITUDE IS NOT NULL, 1, 0) DESC,
        ZIP
    ) AS RN
  FROM src
)
SELECT
  ZIP, LATITUDE, LONGITUDE, CITY, STATE, TIMEZONE,
  IS_DAYLIGHT_SAVINGS,
  GEOPOINT, DMA_ID, DMA_NAME,
  TOTAL_POPULATION, MEDIAN_AGE, TOTAL_MALE_POPULATION, TOTAL_FEMALE_POPULATION
FROM dedup
WHERE RN = 1;

-- Validácie
SELECT COUNT(*) AS rows_clean FROM ZIP_CODE_METADATA_CLEAN;

SELECT COUNT(*) AS distinct_zip
FROM (SELECT DISTINCT ZIP FROM ZIP_CODE_METADATA_CLEAN);

SELECT ZIP, COUNT(*) cnt
FROM ZIP_CODE_METADATA_CLEAN
GROUP BY ZIP
HAVING COUNT(*) > 1;

USE SCHEMA DW;

-- =========================
-- DIM_LOAD_DATE
-- =========================
CREATE OR REPLACE TABLE DIM_LOAD_DATE AS
SELECT
  1 AS LOAD_DATE_ID,
  CURRENT_DATE() AS LOAD_DATE;

-- =========================
-- DIM_DMA_USA
-- =========================
CREATE OR REPLACE TABLE DIM_DMA_USA AS
SELECT
  ROW_NUMBER() OVER (ORDER BY DMA_ID, DMA_NAME) AS DMA_USA_ID,
  DMA_ID,
  DMA_NAME
FROM (
  SELECT DISTINCT DMA_ID, DMA_NAME
  FROM ROOSTER_PROJECT_DB.STAGING.ZIP_CODE_METADATA_CLEAN
);

-- =========================
-- DIM_GEO_USA
-- =========================
CREATE OR REPLACE TABLE DIM_GEO_USA AS
SELECT
  ROW_NUMBER() OVER (
    ORDER BY LATITUDE, LONGITUDE, TIMEZONE, IS_DAYLIGHT_SAVINGS
  ) AS GEO_USA_ID,
  LATITUDE,
  LONGITUDE,
  TIMEZONE,
  IS_DAYLIGHT_SAVINGS
FROM (
  SELECT DISTINCT
    LATITUDE, LONGITUDE, TIMEZONE, IS_DAYLIGHT_SAVINGS
  FROM ROOSTER_PROJECT_DB.STAGING.ZIP_CODE_METADATA_CLEAN
);

-- =========================
-- DIM_DEMOGRAPHICS_USA
-- =========================
CREATE OR REPLACE TABLE DIM_DEMOGRAPHICS_USA AS
SELECT
  ROW_NUMBER() OVER (
    ORDER BY TOTAL_POPULATION, MEDIAN_AGE
  ) AS DEMOGRAPHICS_USA_ID,
  TOTAL_POPULATION,
  MEDIAN_AGE,
  TOTAL_MALE_POPULATION,
  TOTAL_FEMALE_POPULATION
FROM (
  SELECT DISTINCT
    TOTAL_POPULATION,
    MEDIAN_AGE,
    TOTAL_MALE_POPULATION,
    TOTAL_FEMALE_POPULATION
  FROM ROOSTER_PROJECT_DB.STAGING.ZIP_CODE_METADATA_CLEAN
);

-- =========================
-- DIM_ZIP_USA
-- =========================
CREATE OR REPLACE TABLE DIM_ZIP_USA AS
SELECT
  ROW_NUMBER() OVER (ORDER BY ZIP) AS ZIP_USA_ID,
  ZIP,
  CITY,
  STATE
FROM (
  SELECT DISTINCT ZIP, CITY, STATE
  FROM ROOSTER_PROJECT_DB.STAGING.ZIP_CODE_METADATA_CLEAN
);

-- =========================
-- FACT_ZIP_USA_SNAPSHOT
-- =========================
CREATE OR REPLACE TABLE FACT_ZIP_USA_SNAPSHOT AS
WITH base AS (
  SELECT
    c.ZIP,
    c.STATE,
    c.DMA_ID,
    c.DMA_NAME,
    c.LATITUDE,
    c.LONGITUDE,
    c.TIMEZONE,
    c.IS_DAYLIGHT_SAVINGS,
    c.TOTAL_POPULATION,
    c.MEDIAN_AGE,
    c.TOTAL_MALE_POPULATION,
    c.TOTAL_FEMALE_POPULATION,
    1 AS ZIP_COUNT,
    RANK() OVER (
      PARTITION BY c.STATE
      ORDER BY c.TOTAL_POPULATION DESC NULLS LAST
    ) AS POPULATION_RANK_IN_STATE,
    SUM(c.TOTAL_POPULATION) OVER (
      PARTITION BY c.STATE
    ) AS STATE_TOTAL_POPULATION,
    LAG(c.TOTAL_POPULATION) OVER (
      PARTITION BY c.STATE
      ORDER BY c.ZIP
    ) AS PREVIOUS_ZIP_POPULATION
  FROM ROOSTER_PROJECT_DB.STAGING.ZIP_CODE_METADATA_CLEAN c
)
SELECT
  ROW_NUMBER() OVER (ORDER BY b.ZIP) AS FACT_ZIP_USA_SNAPSHOT_ID,
  z.ZIP_USA_ID,
  g.GEO_USA_ID,
  d.DMA_USA_ID,
  demo.DEMOGRAPHICS_USA_ID,
  ld.LOAD_DATE_ID,
  -- metriky
  b.ZIP_COUNT,
  b.POPULATION_RANK_IN_STATE,
  b.STATE_TOTAL_POPULATION,
  b.PREVIOUS_ZIP_POPULATION
FROM base b
JOIN DIM_ZIP_USA z ON b.ZIP = z.ZIP
JOIN DIM_GEO_USA g ON b.LATITUDE = g.LATITUDE
 AND b.LONGITUDE = g.LONGITUDE
 AND NVL(b.TIMEZONE,'') = NVL(g.TIMEZONE,'')
 AND b.IS_DAYLIGHT_SAVINGS = g.IS_DAYLIGHT_SAVINGS
JOIN DIM_DMA_USA d ON NVL(b.DMA_ID,-1) = NVL(d.DMA_ID,-1)
 AND NVL(b.DMA_NAME,'') = NVL(d.DMA_NAME,'')
JOIN DIM_DEMOGRAPHICS_USA demo ON NVL(b.TOTAL_POPULATION,-1) = NVL(demo.TOTAL_POPULATION,-1)
 AND NVL(b.MEDIAN_AGE,-1) = NVL(demo.MEDIAN_AGE,-1)
 AND NVL(b.TOTAL_MALE_POPULATION,-1) = NVL(demo.TOTAL_MALE_POPULATION,-1)
 AND NVL(b.TOTAL_FEMALE_POPULATION,-1) = NVL(demo.TOTAL_FEMALE_POPULATION,-1)
JOIN DIM_LOAD_DATE ld ON 1=1;

DROP TABLE IF EXISTS ZIP_CODE_METADATA_STAGING;
