ALTER TABLE DIM_ZIP_USA
  ADD CONSTRAINT PK_DIM_ZIP_USA PRIMARY KEY (ZIP_USA_ID);

ALTER TABLE DIM_GEO_USA
  ADD CONSTRAINT PK_DIM_GEO_USA PRIMARY KEY (GEO_USA_ID);

ALTER TABLE DIM_DMA_USA
  ADD CONSTRAINT PK_DIM_DMA_USA PRIMARY KEY (DMA_USA_ID);

ALTER TABLE DIM_DEMOGRAPHICS_USA
  ADD CONSTRAINT PK_DIM_DEMOGRAPHICS_USA PRIMARY KEY (DEMOGRAPHICS_USA_ID);

ALTER TABLE DIM_LOAD_DATE
  ADD CONSTRAINT PK_DIM_LOAD_DATE PRIMARY KEY (LOAD_DATE_ID);

ALTER TABLE FACT_ZIP_USA_SNAPSHOT
  ADD CONSTRAINT PK_FACT_ZIP_USA_SNAPSHOT PRIMARY KEY (FACT_ZIP_USA_SNAPSHOT_ID);



ALTER TABLE FACT_ZIP_USA_SNAPSHOT
  ADD CONSTRAINT FK_FACT_ZIP_USA_ZIP
  FOREIGN KEY (ZIP_USA_ID) REFERENCES DIM_ZIP_USA(ZIP_USA_ID);

ALTER TABLE FACT_ZIP_USA_SNAPSHOT
  ADD CONSTRAINT FK_FACT_ZIP_USA_GEO
  FOREIGN KEY (GEO_USA_ID) REFERENCES DIM_GEO_USA(GEO_USA_ID);

ALTER TABLE FACT_ZIP_USA_SNAPSHOT
  ADD CONSTRAINT FK_FACT_ZIP_USA_DMA
  FOREIGN KEY (DMA_USA_ID) REFERENCES DIM_DMA_USA(DMA_USA_ID);

ALTER TABLE FACT_ZIP_USA_SNAPSHOT
  ADD CONSTRAINT FK_FACT_ZIP_USA_DEMO
  FOREIGN KEY (DEMOGRAPHICS_USA_ID) REFERENCES DIM_DEMOGRAPHICS_USA(DEMOGRAPHICS_USA_ID);

ALTER TABLE FACT_ZIP_USA_SNAPSHOT
  ADD CONSTRAINT FK_FACT_ZIP_USA_LOADDATE
  FOREIGN KEY (LOAD_DATE_ID) REFERENCES DIM_LOAD_DATE(LOAD_DATE_ID);



SELECT GET_DDL('TABLE', 'ROOSTER_PROJECT_DB.DW.DIM_ZIP_USA');
SELECT GET_DDL('TABLE', 'ROOSTER_PROJECT_DB.DW.DIM_GEO_USA');
SELECT GET_DDL('TABLE', 'ROOSTER_PROJECT_DB.DW.DIM_DMA_USA');
SELECT GET_DDL('TABLE', 'ROOSTER_PROJECT_DB.DW.DIM_DEMOGRAPHICS_USA');
SELECT GET_DDL('TABLE', 'ROOSTER_PROJECT_DB.DW.DIM_LOAD_DATE');
SELECT GET_DDL('TABLE', 'ROOSTER_PROJECT_DB.DW.FACT_ZIP_USA_SNAPSHOT');



//Vizualizacie


//Viz 1: Počet ZIP kódov podľa štátu
SELECT z.STATE, COUNT(*) AS ZIP_COUNT
FROM ROOSTER_PROJECT_DB.DW.FACT_ZIP_USA_SNAPSHOT f
JOIN ROOSTER_PROJECT_DB.DW.DIM_ZIP_USA z
  ON f.ZIP_USA_ID = z.ZIP_USA_ID
GROUP BY z.STATE
ORDER BY ZIP_COUNT DESC;

//Viz 2: Top 20 ZIP podľa populácie
SELECT
  z.ZIP,
  z.CITY,
  z.STATE,
  d.TOTAL_POPULATION
FROM ROOSTER_PROJECT_DB.DW.FACT_ZIP_USA_SNAPSHOT f
JOIN ROOSTER_PROJECT_DB.DW.DIM_ZIP_USA z
  ON f.ZIP_USA_ID = z.ZIP_USA_ID
JOIN ROOSTER_PROJECT_DB.DW.DIM_DEMOGRAPHICS_USA d
  ON f.DEMOGRAPHICS_USA_ID = d.DEMOGRAPHICS_USA_ID
ORDER BY d.TOTAL_POPULATION DESC NULLS LAST
LIMIT 20;

//Viz 3: Top 20 DMA podľa súčtu populácie
SELECT
  dma.DMA_NAME,
  SUM(d.TOTAL_POPULATION) AS TOTAL_POPULATION
FROM ROOSTER_PROJECT_DB.DW.FACT_ZIP_USA_SNAPSHOT f
JOIN ROOSTER_PROJECT_DB.DW.DIM_DMA_USA dma
  ON f.DMA_USA_ID = dma.DMA_USA_ID
JOIN ROOSTER_PROJECT_DB.DW.DIM_DEMOGRAPHICS_USA d
  ON f.DEMOGRAPHICS_USA_ID = d.DEMOGRAPHICS_USA_ID
GROUP BY dma.DMA_NAME
ORDER BY TOTAL_POPULATION DESC NULLS LAST
LIMIT 20;

//Viz 4: Map (Latitude/Longitude body podľa štátu)
SELECT
  dma.DMA_NAME AS DMA,
  SUM(d.TOTAL_POPULATION) AS POPULATION
FROM ROOSTER_PROJECT_DB.DW.FACT_ZIP_USA_SNAPSHOT f
JOIN ROOSTER_PROJECT_DB.DW.DIM_DMA_USA dma
  ON f.DMA_USA_ID = dma.DMA_USA_ID
JOIN ROOSTER_PROJECT_DB.DW.DIM_DEMOGRAPHICS_USA d
  ON f.DEMOGRAPHICS_USA_ID = d.DEMOGRAPHICS_USA_ID
GROUP BY dma.DMA_NAME
ORDER BY POPULATION DESC
LIMIT 15;

//Viz 5: Histogram / bucket – Median age (stĺpce)
SELECT
  FLOOR(d.MEDIAN_AGE) AS AGE_BUCKET,
  COUNT(*) AS ZIP_COUNT
FROM ROOSTER_PROJECT_DB.DW.FACT_ZIP_USA_SNAPSHOT f
JOIN ROOSTER_PROJECT_DB.DW.DIM_DEMOGRAPHICS_USA d
  ON f.DEMOGRAPHICS_USA_ID = d.DEMOGRAPHICS_USA_ID
WHERE d.MEDIAN_AGE IS NOT NULL
GROUP BY AGE_BUCKET
ORDER BY AGE_BUCKET;
